### ISSUE TITLE
+=, -=, *=, /= operators cause error.

### ISSUE THREAD

**Issue by gustason** [BalticAmadeus/AblFormatter#116]
![image](https://github.com/user-attachments/assets/5eba728a-02b9-4dd3-8ad4-3ac554cc234d)

This happens with all similar operators, therefore, all of the lines below cause errors:

``` abl
a += 3.
b -= 3.
c *= 3.
d /= 3.
```

**Comment by eglekaz** [comment]
Fixed with version 0.0.39 of tree-sitter-abl

**Comment by eglekaz** [comment]
Understood the issue.
Registered: https://github.com/usagi-coffee/tree-sitter-abl/issues/86

**Comment by eglekaz** [comment]
All these operators are now recognized as `assignment_operator`. 
Fixed with 0.0.42 version of tree-sitter-abl.
