### ISSUE TITLE
An error occurs when accessing after ()

### ISSUE THREAD

**Issue by SSaulenas** [BalticAmadeus/AblFormatter#150]
Example, this:
```
oObject:Length = new OpenEdge.Core.String(pcMessage):Size
```

Becomes this in assign statement: 
```
oObject:Length = new OpenEdge.Core.String(pcMessage) :Size
```
![image](https://github.com/user-attachments/assets/839f8772-2dd5-407e-a54d-a7e611597fb4)

**Comment by eglekaz** [comment]
fixed with version 0.0.39 of tree-sitter-abl
