### ISSUE TITLE
Buffer-create throw error

### ISSUE THREAD

**Issue by SSaulenas** [BalticAmadeus/AblFormatter#158]
Example,

```progress
something:buffer-create.
```
also,
```progress
something:buffer-value.
```

![image](https://github.com/user-attachments/assets/1cff3d73-0017-4b8e-899a-af7bd640b312)

**Comment by eglekaz** [comment]
`something:buffer-create` is not a good example. According to the documentation, it has to go together with parentheses, even if those are empty. 
Opening a ticket for `something:buffer-value`, since parentheses are optional.
Registered: https://github.com/usagi-coffee/tree-sitter-abl/issues/101

**Comment by eglekaz** [comment]
Fixed with version 0.0.45 of tree-sitter-abl
