### ISSUE TITLE
parameters of external procedure call are not parsed

### ISSUE THREAD

**Issue by eglekaz** [BalticAmadeus/AblFormatter#171]
Example:
`run getMyNumber.p(piFirstNum, piSecNum).`

Calls for internal procedures are being parsed correctly.

Reference:
https://documentation.progress.com/output/ua/OpenEdge_latest/pdsoe/PLUGINS_ROOT/com.openedge.pdt.langref.help/rfi1424920323961.html

**Comment by PauliusKu** [comment]
I see was fixed on tree-sitter side, can we close this ticket?

**Comment by eglekaz** [comment]
Tested.
Fixed with 0.0.39 version of tree-sitter-abl
