### ISSUE TITLE
Temp-table fields are not parsed correctly

### ISSUE THREAD

**Issue by gustason** [BalticAmadeus/AblFormatter#192]
For example, in the code
``` abl
DEFINE TEMP-TABLE temp-item
    FIELD cat-page LIKE Item.CatPage
FIELD a AS CHARACTER
FIELD b AS CHARACTER.
```
all the fields after the first one do not get parsed as ```field_definition```.
![image](https://github.com/user-attachments/assets/8bb33ac9-cb14-4183-80e3-2bbd3db8a7de)

**Comment by eglekaz** [comment]
Registered: https://github.com/usagi-coffee/tree-sitter-abl/issues/79

**Comment by PauliusKu** [comment]
Closing as fixed
