### ISSUE TITLE
NO-PREFETCH not parsed as part of find statement

### ISSUE THREAD

**Issue by gustason** [BalticAmadeus/AblFormatter#194]
For example,
``` abl
FIND FIRST Customer NO-LOCK NO-PREFETCH.
```
the find statement gets only parsed up until NO-LOCK:
![image](https://github.com/user-attachments/assets/6c6d05e5-4b43-4c70-8773-508efacd6a3a)

**Comment by eglekaz** [comment]
Registered: https://github.com/usagi-coffee/tree-sitter-abl/issues/89

**Comment by eglekaz** [comment]
Fixed with version 0.0.43 of tree-sitter-abl
