### ISSUE TITLE
define shared stream gets parsed as an error

### ISSUE THREAD

**Issue by gustason** [BalticAmadeus/AblFormatter#224]
For example,
``` abl
define NEW SHARED STREAM rpt.
```
and
``` abl
define SHARED STREAM rpt.
```
get parsed as errors:
![image](https://github.com/user-attachments/assets/99ed085f-0424-4056-ada0-166a9c054f1e)

**Comment by eglekaz** [comment]
Registered: https://github.com/usagi-coffee/tree-sitter-abl/issues/94

**Comment by eglekaz** [comment]
Fixed with version 0.0.44 of tree-sitter-abl
