### ISSUE TITLE
Prettier?

### ISSUE THREAD

**Issue by lievendf** [BalticAmadeus/AblFormatter#228]
Hi,

I recently bumped into the popular [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension.
Extra language support can be provided through [plugins](https://prettier.io/docs/en/plugins.html#community-plugins).
I assume adding ABL support to this extension probably has nothing in common with the AblFormatter extension?

Regards,
Lieven

**Comment by PauliusKu** [comment]
Hi @lievendf,

we don't have this planed at the moment, but I think in theory it would be possible to remake this standalone formatter into a plugin for prettier. But currently I don't see many benefits, as all formatting (and parsing) logic still has to be implemented for ABL more or less from scratch.

Thanks for your interest though.
