### ISSUE TITLE
MOD operator parsed as error

### ISSUE THREAD

**Issue by gustason** [BalticAmadeus/AblFormatter#230]
``` abl
ibitnum = ipos MOD 8.
```
![image](https://github.com/user-attachments/assets/7c21c86a-5495-4b01-9260-88956fadf6f1)

**Comment by eglekaz** [comment]
Registered: https://github.com/usagi-coffee/tree-sitter-abl/issues/93

**Comment by eglekaz** [comment]
Fixed with version 0.0.43 of tree-sitter-abl
