### ISSUE TITLE
VSIX missing

### ISSUE THREAD

**Issue by simondrum** [BalticAmadeus/AblFormatter#266]
Hi,

I wanted to do some tests on a small project of mine, could you add the vsix to the repo please? 
Thanks :)

**Comment by PauliusKu** [comment]
Hi @simondrum 
we usually add vsix under release tag as an asset: https://github.com/BalticAmadeus/AblFormatter/releases

0.0.3 is currently the newest version

**Comment by simondrum** [comment]
Oh thanks I forgot to check there!
