### ISSUE TITLE
Conditional using statements should not be sorted

### ISSUE THREAD

**Issue by ccecvb** [BalticAmadeus/AblFormatter#276]
I formatted a source containing conditional `using ` statements

The usings are sorted without taking the conditional code into account

e.g.
`using be.cce.SmartTools.Images.ImageProvider           from propath.` is moved out of the &if
`using be.cce.ccetools.tools.I18N                       from propath.` is moved into the &if

![image](https://github.com/user-attachments/assets/4e8b0728-20d5-4f80-8bd3-4f0128a36a5d)

**Comment by PauliusKu** [comment]
Yep, that's an issue here. I'm not sure if we'll be able to solve this without fixing preprocessor directives. But we'll try.

**Comment by ccecvb** [comment]
No need to try for me
If the preprocessor directives are not formatted correctly, this source has to be fixed manually, after formatting, anyway.
Fixing preprocessor directives would have a higher priority for me because appbuilder defines are changed incorrectly as well

`&if defined` becomes `&IFdefineD`
![image](https://github.com/user-attachments/assets/9c015c52-f4c5-4c44-95a5-10e9f8aa38fa)
